### ISSUE TITLE
RuntimeError: NCCL error in: /pytorch/torch/lib/c10d/ProcessGroupNCCL.cpp:31, unhandled cuda error, NCCL version 2.7.8

### ISSUE THREAD

**Issue by YanhaoWu** [PRBonn/segcontrast#11]
When I use "python3 contrastive_train.py --use-cuda --use-intensity --segment-contrast --checkpoint segcontrast" to train the model, the error occurred.

this is my env:
CUDA:11.1
GPU: RTX3090
python: 3.7.13

and other parts are the same as requirements.txt required

I am looking forward to your reply

**Comment by nuneslu** [comment]
Hi, in my setup I have CUDA: 10.2
However, in another setup I could run it using torch 1.9.0 and CUDA 11.1. So you can install torch 1.9.0 after installing the `requirements.txt` with:
`pip3 install torch==1.9.0+cu111 torchvision==0.10.0 -f https://download.pytorch.org/whl/torch_stable.html`

But then you should install `MinkowskiEngine` from the latest version to compile it with the new version of pytorch:
`pip3 install -U git+https://github.com/NVIDIA/MinkowskiEngine --install-option="--blas=openblas" -v --no-deps`

With this you should be able to run the `contrastive_train.py`script without problems.

**Comment by YanhaoWu** [comment]
> Hi, in my setup I have CUDA: 10.2 However, in another setup I could run it using torch 1.9.0 and CUDA 11.1. So you can install torch 1.9.0 after installing the `requirements.txt` with: `pip3 install torch==1.9.0+cu111 torchvision==0.10.0 -f https://download.pytorch.org/whl/torch_stable.html`
> 
> But then you should install `MinkowskiEngine` from the latest version to compile it with the new version of pytorch: `pip3 install -U git+https://github.com/NVIDIA/MinkowskiEngine --install-option="--blas=openblas" -v --no-deps`
> 
> With this you should be able to run the `contrastive_train.py`script without problems.

Thank you !

**Comment by YanhaoWu** [comment]
> Hi, in my setup I have CUDA: 10.2 However, in another setup I could run it using torch 1.9.0 and CUDA 11.1. So you can install torch 1.9.0 after installing the `requirements.txt` with: `pip3 install torch==1.9.0+cu111 torchvision==0.10.0 -f https://download.pytorch.org/whl/torch_stable.html`
> 
> But then you should install `MinkowskiEngine` from the latest version to compile it with the new version of pytorch: `pip3 install -U git+https://github.com/NVIDIA/MinkowskiEngine --install-option="--blas=openblas" -v --no-deps`
> 
> With this you should be able to run the `contrastive_train.py`script without problems.

May I ask how long it will take you to complete the training of 200 epochs? I feel that the training time is a little long...maybe I can't afford it

**Comment by nuneslu** [comment]
Hi, in my setup I was using 4 GPUs with 12Gb each and it took one week for the pre-training.
