### ISSUE TITLE
about the GPU memory

### ISSUE THREAD

**Issue by YanhaoWu** [PRBonn/segcontrast#12]
I am trying to train the model with the code:
```
python3 contrastive_train.py --use-cuda --use-intensity --segment-contrast --checkpoint segcontrast
```
but I found that GPUs have different loads,just like
![N8KQICL515~)20U_VRK4`ZL](https://user-images.githubusercontent.com/79640383/170213300-687554cc-1042-4722-8a9c-aae91c3f4296.png)

this prevents me from setting bigger batch_size to speed up my training, is there any way to sovle this?

I am looking forward to your reply!Thank you !

**Comment by nuneslu** [comment]
I also noticed the same behavior in mine, this is because of pytorch lightning accelerator for the parallel processing. You can maybe try using a different accelerator [here](https://pytorch-lightning.readthedocs.io/en/stable/accelerators/gpu.html#distributed-modes)

**Comment by YanhaoWu** [comment]
> I also noticed the same behavior in mine, this is because of pytorch lightning accelerator for the parallel processing. You can maybe try using a different accelerator [here](https://pytorch-lightning.readthedocs.io/en/stable/accelerators/gpu.html#distributed-modes)

hello, I found that, if I change the code
```
self.model_q = model(in_channels=4 if args.use_intensity else 3, out_channels=latent_features[args.sparse_model]).type(dtype)
self.head_q = model_head(in_channels=latent_features[args.sparse_model], out_channels=args.feature_size).type(dtype)
self.model_k = model(in_channels=4 if args.use_intensity else 3, out_channels=latent_features[args.sparse_model]).type(dtype)
self.head_k = model_head(in_channels=latent_features[args.sparse_model], out_channels=args.feature_size).type(dtype)
```
to
```
self.model_q = model(in_channels=4 if args.use_intensity else 3, out_channels=latent_features[args.sparse_model])
self.head_q = model_head(in_channels=latent_features[args.sparse_model], out_channels=args.feature_size)
self.model_k = model(in_channels=4 if args.use_intensity else 3, out_channels=latent_features[args.sparse_model])
self.head_k = model_head(in_channels=latent_features[args.sparse_model], out_channels=args.feature_size)
```
the GPU load is balance, just like 
![`HIR{7EUO{MKT97 @O4FM(3](https://user-images.githubusercontent.com/79640383/170486885-db473f73-da39-46a0-afb9-5138dfffb1c7.png)

**Comment by WYHbxer** [comment]
> se_model], out_chan
