### ISSUE TITLE
Can segcontrast be implemented on S3DIS without changing a lot of code?

### ISSUE THREAD

**Issue by SC-shendazt** [PRBonn/segcontrast#16]
Can segcontrast be implemented on S3DIS without changing a lot of code?

**Comment by nuneslu** [comment]
Hi, it should be possible. The only thing that is necessary is to check how the clustered instances look like (output from this [function](https://github.com/PRBonn/segcontrast/blob/10102d25d98d6cb73a6f71f98d9eb42dcf3ad5e9/pcd_utils/pcd_preprocess.py#L57)). You can then adjust the hyperparameters from the [plane fitting](https://github.com/PRBonn/segcontrast/blob/10102d25d98d6cb73a6f71f98d9eb42dcf3ad5e9/pcd_utils/pcd_preprocess.py#L62) and from [DBSCAN](https://github.com/PRBonn/segcontrast/blob/10102d25d98d6cb73a6f71f98d9eb42dcf3ad5e9/pcd_utils/pcd_preprocess.py#L47) to extract good clusters from the S3DIS data.

**Comment by SC-shendazt** [comment]
> Hi, it should be possible. The only thing that is necessary is to check how the clustered instances look like (output from this [function](https://github.com/PRBonn/segcontrast/blob/10102d25d98d6cb73a6f71f98d9eb42dcf3ad5e9/pcd_utils/pcd_preprocess.py#L57)). You can then adjust the hyperparameters from the [plane fitting](https://github.com/PRBonn/segcontrast/blob/10102d25d98d6cb73a6f71f98d9eb42dcf3ad5e9/pcd_utils/pcd_preprocess.py#L62) and from [DBSCAN](https://github.com/PRBonn/segcontrast/blob/10102d25d98d6cb73a6f71f98d9eb42dcf3ad5e9/pcd_utils/pcd_preprocess.py#L47) to extract good clusters from the S3DIS data.
Hopefully you can update how to change the loading of the custom dataset to fit the Segcontrast pipeline, such as S3DIS

**Comment by nuneslu** [comment]
On our new paper we have a new method for pre-training and in there we have some tips on how to implement a new dataloader for the model: https://github.com/PRBonn/TARL
