### ISSUE TITLE
inference_vis.py -> ERROR: kernel must be CUDA.

### ISSUE THREAD

**Issue by AbhishekKaushikCV** [PRBonn/segcontrast#19]
Hi @nuneslu, thanks for sharing this great work.

I am trying to setup the environment, and run the 'inference_vis.py' on semantic kitti but I am getting error while running the inference.

I am using the docker image (nuneslu/segcontrast:minkunet) that you provided, and then I started the container with this image with all gpus.  With this container I am getting kernel image error. [Similar ERROR:](https://github.com/pytorch/pytorch/issues/31285)
```RuntimeError: CUDA error: no kernel image is available for execution on the device``` 

In the above issue the solution was to update the torch. So, I updated the torch and reinstalled the MinkowskiEngine. -> Successfully installed. Following your commands mention in this issue: [GitHub Issue](https://github.com/PRBonn/segcontrast/issues/11) .

My current container environment: 
![now_torch_env](https://github.com/PRBonn/segcontrast/assets/51156209/d8864dd3-fcfe-4467-ac0c-bee53bd091b7)
Minkowski Diagnostics:
![now_me_env](https://github.com/PRBonn/segcontrast/assets/51156209/7842c50d-daee-473e-9bf4-21526f50c13c)

**Now: I am getting this error:**
![now_kernel_must_be_cuda_error](https://github.com/PRBonn/segcontrast/assets/51156209/ac4998c9-8a85-48f9-95aa-6fd055034929)

- You also face this error before: [ME_GitHub_Issue](https://github.com/NVIDIA/MinkowskiEngine/issues/296).
- Can you please tell me how did you resolve this error? 
- I don't know what wrong am i doing?
- If you can provide the running version of docker image, that would be really helpful.

Thanks in advance!!!

**Comment by nuneslu** [comment]
Hi! You can try passing the model to cuda device after line 141 adding _resnet = resnet.cuda()_ and _classifier = classifier.cuda()_

The problem with the docker image is that it is hard to provide the docker with the correct CUDA version, and therefore depending on your CUDA version the docker image will not work properly. You can try changing the cuda version in the dockerfile and rebuild it, and then compile the minkowski engine afterwards.

**Comment by AbhishekKaushikCV** [comment]
Yes, passing the model to cuda solved the issue.

Thank you very much for the response.
