### ISSUE TITLE
question about why disable batch_shuffle_ddp

### ISSUE THREAD

**Issue by jackmsye** [PRBonn/segcontrast#7]
hello, thx for your great work. 
I have a question why you disable ddp shuffle. See https://github.com/PRBonn/segcontrast/blob/main/models/moco.py#L306

**Comment by nuneslu** [comment]
I have used as a basis the moco implementation from [DepthContrast](https://github.com/facebookresearch/DepthContrast) and in their implementation they also disable it (see [issue](https://github.com/facebookresearch/DepthContrast/issues/18)). In my case, I have implemented and tested but there was no difference, so I keep it disabled to keep consistent with their implementation.
